### ISSUE TITLE
TypeError: compile() expected string without null bytes

### ISSUE THREAD

**Issue by mdonahoe** [ymichael/cprofilev#26]
Tried to use your package and it didn't work, so I gave up and used pstats instead
$ python -m cprofilev profile_output 
[cProfileV]: cProfile output available at http://127.0.0.1:4000
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/cprofilev.py", line 238, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/cprofilev.py", line 221, in main
    code = compile(fp.read(), progname, 'exec')
TypeError: compile() expected string without null bytes

**Comment by claradaia** [comment]
I have the same problem. Somebody in stackoverflow thinks it might be due to "mismatch between cProfile and cProfilev versions". What versions should I use for python 2.7?

**Comment by claradaia** [comment]
Found the problem. The correct usage for cprofile output files is 
```$ cprofilev -f /path/to/cprofile/output```

Otherwise it will treat the argument as a script you mean to profile.

(long version:
In the original post I was reading, [https://ymichael.com/2014/03/08/profiling-python-with-cprofile.html](url), it says "Call it with your cprofile output: 

```$ cprofilev /path/to/cprofile/output```". 

Which throws the compile() error.

(But wait. Why compile anything? Isn't it just formatting stuff?)

So I ran it with no arguments, which gave me the correct usage:
```
$ cprofilev
usage: cprofilev [--version] [-a ADDRESS] [-p PORT] scriptfile [arg] ...

An easier way to use cProfile.

positional arguments:
  scriptfile            The python script file to run and profile.

optional arguments:
[...]
  -f FILE, --file FILE  cProfile output to view.
                        If specified, the scriptfile provided will be ignored.
```

Shame on me, there's even a warning about the usage updates in the original post, right before the instructions.)

**Comment by iteal** [comment]
Same for me! I followed the instructions on this blog post and nearly uninstalled the package right away
https://ymichael.com/2014/03/08/profiling-python-with-cprofile.html
Can you update this post?

**Comment by ymichael** [comment]
Just updated! Thanks for catching this!
https://github.com/ymichael/psite/commit/f7d26fb8fbf3dfec60a2e8a3407f4a8fb1183cd3
